@startuml sequence
Alice -> John : Hello John, how are you?
loop Healthcheck
    John -> John : Fight against hypochondria
end
note right of John : Rational thoughts!
John --> Alice : Great!
John -> Bob : How about you?
Bob --> John : Jolly good!
@enduml
